version: '3'
services:
  db:
    restart: on-failure:5
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Tokyo
    # volumes:
    #   - ./db/data:/var/lib/mysql
    networks:
      - bot

  discordbot:
    image: discordbot
    restart: always
    build:
      context: app
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "start"]
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_PORT=${DB_PORT}
      - TOKEN=${TOKEN}
      - TZ=Asia/Tokyo
    networks:
      - bot
    depends_on:
      - db

networks:
  bot:
