services:
  db:
    restart: on-failure:5
    image: mysql:8.3.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Tokyo
    volumes:
      - dbdata:/var/lib/mysql

  discordbot:
    image: discordbot
    restart: unless-stopped
    build:
      context: app
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "start"]
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_PORT=${DB_PORT}
      - TOKEN=${TOKEN}
      - TZ=Asia/Tokyo
    depends_on:
      - db

volumes:
  dbdata:
