version: '3'
services:
  db:
    container_name: F2D-DB
    restart: on-failure:5
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Tokyo
    volumes:
      - ./db/data:/var/lib/mysql:z
      - ./db/conf:/etc/mysql/conf.d:z
    ports:
      - ${DB_PORT}:3306
    networks:
      - bot

  discordbot:
    container_name: F2D-BOT
    image: discordbot
    restart: on-failure:5
    build:
      context: src
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_PORT=${DB_PORT}
      - TOKEN=${TOKEN}
      - TZ=Asia/Tokyo
    volumes:
      - ./src:/src:z
    networks:
      - bot
    depends_on:
      - db

networks:
  bot:
